name: Build extension
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Instal VSCE
        run: npm install -g vsce
      - name: Build
        run: vsce package -o mapcomplete.vsix
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mapcomplete
          path: mapcomplete.vsix
